apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-blog-web-deployment
  labels:
    app: sc-blog-web
    kubernetes.io/name: sc-blog-web
    kubernetes.io/component: frontend
    kubernetes.io/version: "1.0.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sc-blog-web
  template:
    metadata:
      labels:
        app: sc-blog-web
    spec:
      containers:
        - name: sc-blog-web-container
          image: localhost:32000/sc-blog-web:latest
          resources:
            limits:
              cpu: 2
              memory: 1Gi
          ports:
            - containerPort: 80
          #env:
          #  - name: API_ENDPOINT
          #    valueFrom:
          #      configMapKeyRef:
          #        name: sc-blog-web-configmap
          #        key: API_ENDPOINT